[package]
name = "mdman"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
jiff = "0.2.5"
markdown = "1.0.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
